### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by cecilianor** [ThomasMACHINE/SchedulePlanner-DBS-Project#10]
Activites that must be done to complete the project. Beware null- and not-null values with foreign keys in tables!

## CRITICAL
1. Create test data
2. Create SQL statements
3. Start writing the report
4. Check with how to deal with foreign keys when nulling values in tables

## Documentation for the Report
- [ ] Design a conceptual model
- [ ] Write reflection note about peer review
- [ ] Design a logical model
- [ ] Apply normalization
- [ ] Implement logical model i PHP

## Other Tasks
- [ ] Confirm that the tables are in BCNF (Cecilia will check this)
- [ ] Create Python API
- [ ] Create SQL code and SQL schemas (Everyone)
- [ ] Create test data for all tables (Everyone)
- [ ] Write the final report
- [ ] Examine how to deal with not-null and null values when adding/altering/deleting tables with foreign keys.
